build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  script:
    - echo "This job tests somthing"
  
test-job2:
  stage: test
  script:
    - echo "This job tests somthing, but takes more time than test-job1"
    - sleep 20


# deploy-prod:
#   stage: deploy
#   script:
